### ISSUE TITLE
No Release Notes for Last Two Updates

### ISSUE THREAD

**Issue by IIAIronWolf** [Limych/ha-blueprint#92]
There have been no release notes for the last two updates. I don't typically update integrations that provide no information on why the update is needed.

**Comment by Limych** [comment]
I beg your pardon. Release descriptions are generated automatically. Something broke there. For now, I don't have the strength to fix it. I will fix it later.

In connection with the situation around Russia and Ukraine, I also want to state that I am apolitical in my projects - my code is written for people around the world, regardless of their nationality, gender, race, religion, etc. You can be calm for any unnecessary inserts in my code.

**Comment by IIAIronWolf** [comment]
All good. Just wanted to let it be known that there was an issue with that. :)

I'm not sure why the remark about nationality, gender, etc. because I didn't say anything about that. Were you replying to something someone else said?

**Comment by Limych** [comment]
No.  I made a remark in order to state my position on this issue and exclude possible suspicions in the future.
